Common:
  # Some configurations are shared across multiple modules in Odometry, so I write them here.
  device: &device cuda
  max_depth: &max_depth auto

Odometry:
  name: MACVO
  args:
    # Device directive to the VO system
    # NOTE: the system may not follow this device config strictly since some module
    # e.g. those rely on PWC-Net, only support running on cuda device.
    device: *device
    edgewidth: 32
    num_point: 200 # Upper bound of KPs in each frame

    # Match covariance for keypoint on first observation (sub-pixel uncertainty
    # caused by the quantized pixel)
    match_cov_default: 0.25

    # Profiling the system using torch, generate chrome json trace file.
    profile: false

  cov:
    obs:
      type: MatchCovariance
      args:
        device: *device
        kernel_size: 31
        match_cov_default: 0.25
        min_depth_cov: 0.05
        min_flow_cov: 0.25

  keypoint:
    type: CovAwareSelector_NoDepth
    args:
      device: *device
      kernel_size: 3
      mask_width: 16
      max_match_cov: 100.0
  
  frontend:
    type: UniMatchCovFrontend
    args:
      weight: /home/airlab/workspace/MAC-SLAM-ROS2/MACVO_ROS2/src/Model/UniMatch/scale2.pth
      device: *device
      dtype : fp32
      model :
          task: flow
          num_refine: 0

          num_scales: 1
          feature_channels: 128
          upsample_factor: 8
          num_head: 1
          ffn_dim_expansion: 4
          num_transformer_layer: 6
          attn_type: swin

          attn_splits_list: [2]
          corr_radius_list: [-1]
          prop_radius_list: [-1]

          cov_model: "FormerCovHead"

  # frontend:
  #   type: FlowFormerCovFrontend
  #   args:
  #     device: *device
  #     weight: /home/airlab/workspace/MAC-SLAM-ROS2/build/MACVO_ROS2/build/lib/MACVO_ROS2/src/Model/MACVO_FrontendCov.pth
  #     use_jit: true
  #     enforce_positive_disparity: false
  #     dtype: fp32

  motion:
    type: StaticMotionModel
    args:

  outlier:
    type: FilterCompose
    args:
      verbose: false
      filter_args:
        - type: CovarianceSanityFilter
          args:
        - type: SimpleDepthFilter
          args:
            min_depth: 0.05
            max_depth: *max_depth
        - type: LikelyFrontOfCamFilter
          args:
  
  postprocess:
    type: DisplacementInterpolate
    args:
  
  keyframe:
    type: AllKeyframe
    args:
  
  optimizer:
    type: PyPoseTwoFramePGO
    args:
      device: cpu
      vectorize: true
      parallel: true

Camera:
  fx: 732.527587890625
  fy: 732.527587890625
  cx: 982.960693359375
  cy: 660.4515991210938
  bl: 0.120022

  width: 1920
  height: 1200
