Common:
  # Some configurations are shared across multiple modules in Odometry, so I write them here.
  device: &device cuda

Odometry:
  name: MACVO_Mapping
  args:
    # Device directive to the VO system
    # NOTE: the system may not follow this device config strictly since some module
    # e.g. those rely on PWC-Net, only support running on cuda device.
    device: *device
    edgewidth: 32
    num_point: 200 # Upper bound of KPs in each frame

    # Match covariance for keypoint on first observation (sub-pixel uncertainty
    # caused by the quantized pixel)
    match_cov_default: 0.25

    # Profiling the system using torch, generate chrome json trace file.
    profile: false

    # Mapping mode provides the dense mapping
    mapping: true

  cov:
    obs:
      type: MatchCovariance
      args:
        device: *device
        kernel_size: 31
        match_cov_default: 0.25
        min_depth_cov: 0.05
        min_flow_cov: 0.25

  keypoint:
    type: CovAwareSelector_NoDepth
    args:
      device: *device
      kernel_size: 7
      mask_width: 32
      max_match_cov: 100.0

  mappoint:
    # Mapping feature can be conveniently turn off by using 
    # "type: NoKeypointSelector" instead of the config below.
    type: MappingPointSelector
    args:
      device: *device
      max_depth: 5.0
      max_depth_cov: 0.005
      mask_width: 32

  frontend:
    type: CUDAGraph_FlowFormerCovFrontend
    args:
      device: *device
      weight: model/MACVO_FrontendCov.pth
      dtype: fp32
      max_flow: -1
      enforce_positive_disparity: false

  motion:
    type: StaticMotionModel
    args:

  outlier:
    type: CovarianceSanityFilter
    args:
  
  postprocess:
    type: MotionInterpolate
    args:
  
  keyframe:
    type: AllKeyframe
    args:
  
  optimizer:
    type: ReprojectOptimizer
    args:
      device: cpu
      vectorize: true
      parallel: true
      use_fancy_cov: false
      constraint: disparity

Camera:
  fx: 732.527587890625
  fy: 732.527587890625
  cx: 982.960693359375
  cy: 660.4515991210938
  bl: 0.120022

  width: 1920
  height: 1200

  scale_u: 3
  scale_v: 4
